*** DATA FILES ***

Param value;value
Param no value;
Param value semicolon;value;
alpha low char;abcdefghijklmnopqrstuvwxyz
alpha up char;ABCDEFGHIJKLMNOPQRSTUVWXYZ
special char;,.:!?/-+|\_<>@*$%&"'#()[]{}
,.:!?/-+|\_<>@*$%&"'#()[]{};
abcdefghijqlmnopqrstuvwxyz;
ABCDEFGHIJQLMNOPQRSTUVWXYZ;


*** DATA START ***

data_file_name.dp
1;;101;;
Mass[a.m.u];I[cnt/s];Mass[a.m.u];I[cnt/s];
1.00000E+00;0.00000E+00;1.01000E+02;0.00000E+00
1.10000E+00;0.00000E+00;1.01100E+02;0.00000E+00
1.20000E+00;0.00000E+00;1.01200E+02;0.00000E+00

*** DATA END ***

*** ANALYSIS POSITION ***

Analysis position params;
Subsection Test
param1;0
param2;1
Other subsection
param1;1
param2;0

*** ANALYSIS RECIPE ***

Analysis recipe params;

*** ACQUISITION PARAMETERS ***

Acquisition params;

*** MEASUREMENT CONDITIONS, name.ms ***:

Species;param1;param2
1;100.000;100
101;200.000;200

*** MAIN ANALYTICAL PARAMETERS (MAP) ***

MAP params;

*** OPTIONAL INSTRUMENTAL PARAMETERS (OIP) ***

OIP params;

*** ION DETECTOR PARAMETERS ***

Ion detector params;

*** OTHERS ***

Other params;

